### PR TITLE
Proposal for a talk at SciPy 2016

### PR DESCRIPTION
**Pull request by ccordoba12**
@spyder-ide/core-developers, and specially @goanpeca (who wants to be co-author of this talk): please read this proposal for a talk at SciPy 2016 and let us know what you think about it, what things can be improved and what you would like to see besides what I've written.

The deadline to send the proposal is tomorrow, so please try to do it quickly. Sorry for the rush, but I hadn't had time to do this until now :-)

### CODE REVIEW

**Comment by ccordoba12** [comment]
One thing I forgot to mention is that the **Abstract** can be 500 words long (right now it only has only like 100 words). So if you want to help me to expand it, that would be great :-)

**Comment by blink1073** [comment]
I like it, and I prefer a shorter abstract since people will want to skim them quickly to determine whether they want to go to a talk and probably won't want something long.

**Comment by goanpeca** [comment]
If we wanted to add more to the long description we could include:

> 6. Dark Theme for Spyder. Spyder now also includes a Dark theme for the interface.

What about all the work of @blink1073 on having extra token completions for the different languages?

**Comment by ccordoba12** [comment]
Thanks @blink1073 and @goanpeca for your feedback :-)

You're totally right @goanpeca, I'll include @blink1073's work as another point, along with your Dark theme suggestion ;-)

**Pull request merged**
